add_colors-macros-and-FD/BG-selector_create-selector-with-concatenation-define
epi-osdev/TacOS pull request #7
Opened 2022-12-07 21:33 UTC by Shin-gema

2022-12-07 23:08 UTC, pulk66-s requested changes
- Guards name is not good, it must begin and finish by two underscore
- Make tab when defining macro
- Foreground is FG, not FD
- The hell is this code ?
```c
#define C_CONC_(BG, FD) BG##FR
```
- When writing hex, please write `0x` before the value
0 -> 0x0
1 -> 0x1
2 -> 0x2
10 -> 0xA (and not A)
15 -> 0xF (and not F)
etc...

2022-12-08 01:09 UTC, theobori reviewed
- `VGA_white` --> `VGA_WHITE`

2022-12-08 21:02 UTC, pulk66-s approved these changes
Working, but why making two `APPLY_MASK` macro ???

2022-12-09 10:03 UTC, pulk66-s approved these changes

2022-12-09 10:03 UTC, merged